# Generated by Django 4.2.30 on 2026-05-22 21:03

import hashlib

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_api_key_hashes(apps, schema_editor):
    APIKey = apps.get_model("accounts", "APIKey")
    for api_key in APIKey.objects.filter(key_hash__isnull=True).exclude(key=""):
        raw_key = api_key.key
        hashed = hashlib.sha256(raw_key.encode("utf-8")).hexdigest()
        api_key.key = hashed
        api_key.key_hash = hashed
        api_key.key_prefix = raw_key[:16]
        api_key.save(update_fields=["key", "key_hash", "key_prefix"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("schools", "0007_mediaasset"),
        ("accounts", "0009_user_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSchoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INVITED", "Invited"),
                            ("SUSPENDED", "Suspended"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_prefix",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["key_prefix"], name="accounts_ap_key_pre_553cd9_idx"
            ),
        ),
        migrations.RunPython(backfill_api_key_hashes, migrations.RunPython.noop),
        migrations.AddField(
            model_name="userschoolmembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="school_memberships",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="userschoolmembership",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memberships",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="userschoolmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_links",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_links",
                to="accounts.role",
            ),
        ),
        migrations.AddIndex(
            model_name="userschoolmembership",
            index=models.Index(
                fields=["user", "status"], name="accounts_us_user_id_19d640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userschoolmembership",
            index=models.Index(
                fields=["school", "role", "status"],
                name="accounts_us_school__5a2646_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userschoolmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "school", "role"), name="unique_user_school_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_role_permission"
            ),
        ),
    ]
