# Generated by Django 4.2.30 on 2026-05-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_permission_rolepermission_userschoolmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_legacy",
            field=models.BooleanField(
                default=False,
                help_text="Flag to mark legacy plaintext keys that need rotation",
            ),
        ),
    ]
