# Generated by Django 6.0.4 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='principal_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
