# Generated by Django 4.2.30 on 2026-05-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_mediaasset"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_month", models.CharField(db_index=True, max_length=7)),
                ("sms_sent", models.PositiveIntegerField(default=0)),
                ("email_sent", models.PositiveIntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_usage",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Usage",
                "verbose_name_plural": "Communication Usages",
                "unique_together": {("school", "billing_month")},
            },
        ),
    ]
