# Generated by Django 4.2.30 on 2026-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="geofence_radius",
            field=models.IntegerField(
                default=200,
                help_text="Radius in meters within which check-in is allowed",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
