# Generated by Django 4.2.30 on 2026-05-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_geofence_radius_school_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="grace_period_days",
            field=models.IntegerField(
                default=7, help_text="Number of days after expiry before hard lockdown"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="mpesa_transaction_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("FREE", "Free Trial"), ("BASIC", "Basic"), ("PRO", "Pro")],
                default="BASIC",
                max_length=20,
            ),
        ),
    ]
