# Generated by Django 6.0.4 on 2026-04-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schoolsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='principal_name',
            field=models.CharField(default='School Principal', max_length=100),
        ),
    ]
