# Generated by Django 6.0.4 on 2026-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schoolsetting_principal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
