# Generated by Django 4.2.30 on 2026-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_category_subscription_grace_period_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Free Trial"),
                    ("STARTER", "Starter"),
                    ("PROFESSIONAL", "Professional"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="STARTER",
                max_length=20,
            ),
        ),
    ]
