# Generated by Django 4.2.30 on 2026-05-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schools", "0006_alter_subscription_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField()),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("TENANT", "Tenant"),
                            ("PUBLIC", "Public"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEAN", "Clean"),
                            ("INFECTED", "Infected"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["school", "visibility"],
                        name="schools_med_school__d0cbe1_idx",
                    ),
                    models.Index(
                        fields=["scan_status", "created_at"],
                        name="schools_med_scan_st_67d4a3_idx",
                    ),
                    models.Index(
                        fields=["content_type"], name="schools_med_content_86e17f_idx"
                    ),
                ],
            },
        ),
    ]
