# Generated by Django 6.0.4 on 2026-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_schoolsetting_principal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='school_motto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
