# Generated by Django 6.0.4 on 2026-04-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_schoolsetting_school_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
