# Generated by Django 6.0.4 on 2026-05-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="classes.stream",
            ),
        ),
    ]
