# Generated by Django 4.2.30 on 2026-05-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_subjectassignment_unique_together_and_more"),
        ("teachers", "0001_initial"),
        ("lms", "0003_videowatchtime_discussion_studentprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="classes.stream",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="classes.stream",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_resources",
                to="teachers.teacher",
            ),
        ),
    ]
