# Generated by Django 4.2.30 on 2026-05-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("lms", "0004_quiz_stream_resource_stream_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="teachers.teacher",
            ),
        ),
    ]
