# Generated by Django 6.0.4 on 2026-05-08 18:37

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("schools", "0002_school_curriculum_school_status"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_PERFORMANCE", "Student Performance Analysis"),
                            ("ATTENDANCE_TRENDS", "Attendance Trends"),
                            ("FINANCIAL_ANALYTICS", "Financial Analytics"),
                            ("TEACHER_EFFICIENCY", "Teacher Efficiency Metrics"),
                            ("SCHOOL_OVERVIEW", "School Overview Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report_period", models.CharField(default="monthly", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField()),
                ("insights", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DataInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("TREND", "Trend Analysis"),
                            ("ALERT", "Performance Alert"),
                            ("RECOMMENDATION", "Improvement Recommendation"),
                            ("PREDICTION", "Predictive Insight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("data_source", models.CharField(max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                ("actionable", models.BooleanField(default=False)),
                ("action_items", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("GRADE_PREDICTION", "Grade Prediction"),
                            ("ATTENDANCE_RISK", "Attendance Risk Assessment"),
                            ("DROPOUT_RISK", "Dropout Risk Prediction"),
                            ("PERFORMANCE_TRENDS", "Performance Trend Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_data", models.JSONField()),
                (
                    "accuracy_score",
                    models.DecimalField(decimal_places=4, max_digits=5, null=True),
                ),
                ("training_date", models.DateTimeField()),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="predictiverisk",
            options={"ordering": ["-confidence_score"]},
        ),
        migrations.RenameField(
            model_name="predictiverisk",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="predictiverisk",
            name="intervention_notes",
        ),
        migrations.RemoveField(
            model_name="predictiverisk",
            name="intervention_status",
        ),
        migrations.RemoveField(
            model_name="predictiverisk",
            name="reason_summary",
        ),
        migrations.AddField(
            model_name="predictiverisk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 8, 18, 37, 34, 755954, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictiverisk",
            name="factors",
            field=models.JSONField(
                default={}, help_text="Key factors contributing to this risk level."
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="predictiverisk",
            name="confidence_score",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name="predictiverisk",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictive_risks",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="predictiverisk",
            index=models.Index(
                fields=["risk_level", "confidence_score"],
                name="analytics_p_risk_le_6a5524_idx",
            ),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_reports",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="datainsight",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_insights",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_snapshots",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="predictivemodel",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictive_models",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreport",
            index=models.Index(
                fields=["school", "report_type", "created_at"],
                name="analytics_a_school__24b13d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsreport",
            index=models.Index(
                fields=["expires_at"], name="analytics_a_expires_3842d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analyticsreport",
            unique_together={
                ("school", "report_type", "report_period", "start_date", "end_date")
            },
        ),
        migrations.AddIndex(
            model_name="datainsight",
            index=models.Index(
                fields=["school", "insight_type", "created_at"],
                name="analytics_d_school__c74544_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datainsight",
            index=models.Index(
                fields=["actionable", "created_at"],
                name="analytics_d_actiona_892dd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(
                fields=["school", "metric_name", "date"],
                name="analytics_m_school__c15326_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(
                fields=["date", "metric_name"], name="analytics_m_date_373439_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metricsnapshot",
            unique_together={("school", "date", "metric_name")},
        ),
        migrations.AddIndex(
            model_name="predictivemodel",
            index=models.Index(
                fields=["school", "model_type", "is_active"],
                name="analytics_p_school__e03a76_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="predictivemodel",
            unique_together={("school", "model_type")},
        ),
    ]
