# Generated by Django 4.2.30 on 2026-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_mark_exams_mark_exam_id_607e5d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date'], name='exams_exam_start_d_281c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['end_date'], name='exams_exam_end_dat_004a62_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'term'], name='exams_exam_academi_136eac_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published', 'start_date'], name='exams_exam_is_publ_5bcc97_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['subject', 'score'], name='exams_mark_subject_ea2aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['exam', 'score'], name='exams_mark_exam_id_92ffa9_idx'),
        ),
    ]
