# Generated by Django 6.0.4 on 2026-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Rename old table
            ALTER TABLE attendance_dailyattendance RENAME TO attendance_dailyattendance_old;

            -- Create partitioned table
            CREATE TABLE attendance_dailyattendance (
                id bigserial,
                date date NOT NULL,
                status varchar(10) NOT NULL,
                remarks text,
                created_at timestamptz NOT NULL,
                marked_by_id bigint REFERENCES accounts_user(id) ON DELETE SET NULL,
                student_id bigint NOT NULL REFERENCES students_student(id) ON DELETE CASCADE,
                PRIMARY KEY (id, date)
            ) PARTITION BY RANGE (date);

            -- Create initial partitions for 2026
            CREATE TABLE attendance_daily_2026_01 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
            CREATE TABLE attendance_daily_2026_02 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
            CREATE TABLE attendance_daily_2026_03 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
            CREATE TABLE attendance_daily_2026_04 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
            CREATE TABLE attendance_daily_2026_05 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
            CREATE TABLE attendance_daily_2026_06 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
            CREATE TABLE attendance_daily_2026_07 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
            CREATE TABLE attendance_daily_2026_08 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
            CREATE TABLE attendance_daily_2026_09 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
            CREATE TABLE attendance_daily_2026_10 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
            CREATE TABLE attendance_daily_2026_11 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
            CREATE TABLE attendance_daily_2026_12 PARTITION OF attendance_dailyattendance FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
            
            -- Default partition
            CREATE TABLE attendance_daily_default PARTITION OF attendance_dailyattendance DEFAULT;

            -- Copy data if any (though we checked and it's 0)
            -- INSERT INTO attendance_dailyattendance (id, date, status, remarks, created_at, marked_by_id, student_id)
            -- SELECT id, date, status, remarks, created_at, marked_by_id, student_id FROM attendance_dailyattendance_old;

            -- Drop old table
            DROP TABLE attendance_dailyattendance_old;
            """,
            reverse_sql="""
            -- Reverse is basically recreate unpartitioned and copy back
            ALTER TABLE attendance_dailyattendance RENAME TO attendance_dailyattendance_partitioned;
            CREATE TABLE attendance_dailyattendance (
                id bigserial PRIMARY KEY,
                date date NOT NULL,
                status varchar(10) NOT NULL,
                remarks text,
                created_at timestamptz NOT NULL,
                marked_by_id bigint REFERENCES accounts_user(id) ON DELETE SET NULL,
                student_id bigint NOT NULL REFERENCES students_student(id) ON DELETE CASCADE
            );
            INSERT INTO attendance_dailyattendance (date, status, remarks, created_at, marked_by_id, student_id)
            SELECT date, status, remarks, created_at, marked_by_id, student_id FROM attendance_dailyattendance_partitioned;
            DROP TABLE attendance_dailyattendance_partitioned;
            """,
        )
    ]
