# Generated by Django 6.0.4 on 2026-04-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classroom_scheduleslot'),
        ('schools', '0007_schoolsetting_school_motto'),
        ('teachers', '0002_teacher_deleted_at_alter_teacher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='schools.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='classes.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('stream', 'subject')},
            },
        ),
    ]
