# Generated by Django 4.2.30 on 2026-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_scheduleslot_classes_sch_teacher_7d20f5_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="academic_year",
            field=models.CharField(default="2026", max_length=20),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="periods_per_week",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together={("stream", "subject", "academic_year")},
        ),
    ]
