# Generated by Django 4.2.30 on 2026-05-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_subjectassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TERM_1", "Term 1"),
                            ("TERM_2", "Term 2"),
                            ("TERM_3", "Term 3"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_current"], name="classes_aca_is_curr_24fae7_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="classes_aca_start_d_821071_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_academic_year_name"
            ),
        ),
        migrations.AddField(
            model_name="academicterm",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms",
                to="classes.academicyear",
            ),
        ),
        migrations.AddIndex(
            model_name="academicterm",
            index=models.Index(
                fields=["academic_year", "is_current"],
                name="classes_aca_academi_649ec4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicterm",
            index=models.Index(
                fields=["start_date", "end_date"], name="classes_aca_start_d_c9325a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "name"), name="unique_academic_year_term"
            ),
        ),
    ]
